### ISSUE TITLE
3.0 的说我的key太短是为啥

### ISSUE THREAD

**Issue by Dandelion246** [yzh52521/webman-jwt-auth#10]
复制的配置未修改 
            'login_type'    => 'mpo',
            'signer_key'    => 'oP0qmqzHS4Vvml5a',
            'public_key'    => 'file://path/public.key',
            'private_key'   => 'file://path/private.key',
            'expires_at'    => 3600,
            'refresh_ttL'   => 7200,
            'leeway'        => 0,
            'signer'        => 'HS256',
            'type'          => 'Header',
            'auto_refresh'  => false,
            'iss'           => 'webman.client.admin', 

error: Lcobucci\JWT\Signer\InvalidKeyProvided: Key provided is shorter than 256 bits, only 96 bits provided in /Users/prw/Desktop/Quick/peng/webman/vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php:39

**Comment by yuanzhihai** [comment]
'signer_key' => hash("sha256", $string);
