### ISSUE TITLE
把token加入到黑名单中

### ISSUE THREAD

**Issue by yaoayo** [yzh52521/webman-jwt-auth#12]
yzh52521\JwtAuth\BlackList 中的addTokenBlack方法 单点登录 当前时间减1秒 这样会导致 token 验证 yzh52521\JwtAuth\BlackList 中的hasTokenBlack 方法 永远返回 fasle

**Comment by yuanzhihai** [comment]
哪里不对么？

**Comment by yuanzhihai** [comment]
> yzh52521\JwtAuth\BlackList 中的addTokenBlack方法 单点登录 当前时间减1秒 这样会导致 token 验证 yzh52521\JwtAuth\BlackList 中的hasTokenBlack 方法 永远返回 fasle

返回 true的时候不就是别人登录了么

**Comment by yaoayo** [comment]
你试一下单点登录后 调用JwtAuth::logout()方法 之前的token后还能用？

**Comment by yaoayo** [comment]
我这边退出登录后之前的token还能用 包的版本是3.0.2

**Comment by yuanzhihai** [comment]
已修复 升级3.0.3
