### ISSUE TITLE
单点登录自动续签token

### ISSUE THREAD

**Issue by yaoayo** [yzh52521/webman-jwt-auth#13]
验证token时候  Utils::isPast( $claims->get( 'exp' )->getTimestamp(),$leeway ) 这里始终返回 false  导致不能自动续签

**Comment by yuanzhihai** [comment]
> 验证token时候 Utils::isPast( $claims->get( 'exp' )->getTimestamp(),$leeway ) 这里始终返回 false 导致不能自动续签

过期了才返回 true

**Comment by yaoayo** [comment]
你可以试一下 这个自动续签 过期了也是false

**Comment by yuanzhihai** [comment]
> 你可以试一下 这个自动续签 过期了也是false

打印返回 true 啊

**Comment by yaoayo** [comment]
3.0.2 这个版本开启自动续签token  不生效并响应头没有返回续签token

**Comment by yaoayo** [comment]
这个我的配置             

'expires_at'    => 120,
   'refresh_ttL'   => 180,
            'leeway'        => 60,
            'signer'        => 'HS256',
            'type'          => 'Header',
            'auto_refresh'  => true,

**Comment by yuanzhihai** [comment]
我这个插件是从fpm的项目修改过来的  
具体为什么没返回 ，应该是 response的问题

**Comment by yuanzhihai** [comment]
你如果有能力 提交一下pr

**Comment by yaoayo** [comment]
![image](https://github.com/yzh52521/webman-jwt-auth/assets/29781028/667083ef-649b-4ecd-a895-5899ab72d7a4)
是这两个判断问题

**Comment by yuanzhihai** [comment]
不是 判断 
看这个方法
$this->automaticRenewalToken();

**Comment by yaoayo** [comment]
![image](https://github.com/yzh52521/webman-jwt-auth/assets/29781028/36b8edb5-1079-4759-961b-06a58c4f282b)
把 验证token是否存在黑名单 判断移动到最下面 能解决问题

**Comment by yaoayo** [comment]
还需要在 hasTokenBlack 这个方法里面再处理一下 如果开启了自动刷新token 过期后不抛异常

**Comment by yuanzhihai** [comment]
已优化
