### ISSUE TITLE
mpo模式下，首次Token登录就提示Token在黑名单了

### ISSUE THREAD

**Issue by jayazhao** [yzh52521/webman-jwt-auth#14]
看了代码，问题可能出在hasTokenBlack 这个方法里，redis都找不到这个黑名单key，为啥要返回 true？
<img width="965" alt="iShot_2023-10-13_11 50 55" src="https://github.com/yuanzhihai/webman-jwt-auth/assets/13504408/e3e79f62-26eb-444d-a9d0-34689b75adde">

**Comment by yuanzhihai** [comment]
感谢反馈 已更新
