### ISSUE TITLE
unserialize(): Passing null to parameter #1 ($data) of type string is deprecated

### ISSUE THREAD

**Issue by iYting** [yzh52521/webman-jwt-auth#5]
在对着文档测试时 发现以下问题:  

JwtAuth::verify($token); 报错 unserialize(): Passing null to parameter #1 ($data) of type string is deprecated
查看代码发现报错是在BlackList.php文件中hasTokenBlack方法里 
![image](https://user-images.githubusercontent.com/17744874/181211417-67f624fb-9fd5-43b3-af2a-9349ae3121ca.png)
Redis::get($cacheKey) 返回为null 导致unserialize方法报错
我是对着文档一步一步写的 这个报错是否是插件bug?

**Comment by linjiaen** [comment]
遇到同样的问题

**Comment by yuanzhihai** [comment]
升级2.0.13 试试
