### ISSUE TITLE
安装扩展包配好相应参数请求报 Key provided is shorter than 256 bits, only 96 bits provided是缺少什么配置吗？

### ISSUE THREAD

**Issue by ugarden** [yzh52521/webman-jwt-auth#7]
Lcobucci\JWT\Signer\InvalidKeyProvided: Key provided is shorter than 256 bits, only 96 bits provided

**Comment by yuanzhihai** [comment]
https://lcobucci-jwt.readthedocs.io/en/stable/supported-algorithms/ 

signer_key长度 >= 256 bits

**Comment by yuanzhihai** [comment]
$signer_key  = hash('sha256','字符串');  这样

**Comment by ugarden** [comment]
好的，谢谢指导
