### ISSUE TITLE
过期后，第一次生成，然后1-2秒验证不通过，提示黑名单

### ISSUE THREAD

**Issue by wybwsk** [yzh52521/webman-jwt-auth#9]
`//生成
$config = JwtAuth::getConfig(‘应用’);
$token = JwtAuth::token($user['id'], [ ])->toString();
return   [$token,$config->getExpires(),$config->getRefreshTTL()]

//验证
JwtAuth::getConfig('应用');
$payload = JwtAuth::verify($token);
//然后请求带token，中间件验证。。
`
问题重现流程。
1、隔了一晚上，第二天一早来登录，获取token;
2、接口带token，先在中间件进行验证（中间大概只间隔1秒，配置中blacklist_grace_period设置的是0）。
**3、这时报错"The token is in blacklist"**
4、重新获取token，再调接口进行TOKEN验证。成功。
5、重新获取token，再调接口进行TOKEN验证。成功。
6、重新获取token，再调接口进行TOKEN验证。成功。
7、隔了一晚上，从1循环.....

**Comment by wybwsk** [comment]
用的是单点登录，今天又试了一下，早上过来，blacklist。同样的问题。

于是就把redis中的黑名单缓存删除。然后再来。又出现blacklist。查了源码。

问题出在BlackList.php的hasTokenBlack方法中。

```
$iatTime = Utils::getTimeByTokenTime($claims->get(RegisteredClaims::ISSUED_AT))->getTimestamp();
if (!empty($iatTime) && !empty($val['valid_until'])) {
    return $iatTime <= $val['valid_until'];
}
```

如果redis中没有这个黑名单的时候，这个iatTime会和$val['valid_until']的时间戳是一样的。返回true，不通过
如果redis有值时。这个iatTime会比$val['valid_until']大1。。返回false，通过

然后更灵异的是。。过了早上10点。。再次删除redis黑名单。然后获取token，验证token。。这时iatTime就一直比$val['valid_until']大1..

**Comment by yuanzhihai** [comment]
> 用的是单点登录，今天又试了一下，早上过来，blacklist。同样的问题。
> 
> 于是就把redis中的黑名单缓存删除。然后再来。又出现blacklist。查了源码。
> 
> 问题出在BlackList.php的hasTokenBlack方法中。
> 
> ```
> $iatTime = Utils::getTimeByTokenTime($claims->get(RegisteredClaims::ISSUED_AT))->getTimestamp();
> if (!empty($iatTime) && !empty($val['valid_until'])) {
>     return $iatTime <= $val['valid_until'];
> }
> ```
> 
> 如果redis中没有这个黑名单的时候，这个iatTime会和$val['valid_until']的时间戳是一样的。返回true，不通过 如果redis有值时。这个iatTime会比$val['valid_until']大1。。返回false，通过
> 
> 然后更灵异的是。。过了早上10点。。再次删除redis黑名单。然后获取token，验证token。。这时iatTime就一直比$val['valid_until']大1..


iatTime 比$val['valid_until']大1 不对么？ 返回false 就是验证通过啊

**Comment by wybwsk** [comment]
对啊，正常情况下就是iatTime 比$val['valid_until']大1 
但是我会遇到这样。。
当redis中的黑名单是null时，先生成token，再验证TOKEN，这时去看。iatTime 等于$val['valid_until']  这就是异常了。
上面不是验证失败了吗，因为 ==，所以redis这时有值了。这时再生成另一个token，再验证TOKEN，这时去看。iatTime 就比$val['valid_until']大1,  这就正常了。

用到现实场景中就是，当token过了一天过期后，工作人员来登录时，要登两次，第一次.blacklist,第二次，登录成功...

**Comment by yuanzhihai** [comment]
> 当redis中的黑名单是null时

validUntil = Utils::now()->subSeconds( 1 )->getTimestamp();

加入缓冲的时间 减了1秒的啊

**Comment by yuanzhihai** [comment]
你可以改成多减几秒试试

**Comment by wybwsk** [comment]
第一次我打印出来的是
$iatTime              1675472418
$val['valid_until'] 1675472418

第二次打印出来的是
$iatTime               1675472418
$val['valid_until']  1675472417

Lcobucci\JWT\Token 生成的 iat时间 和 Carbon生成的valid_until时间可能在某些情况下不一样。。
当Token生成后，过了一秒，才到Carbon，所以Carbon生成的时间比iat多一秒。。那么subSeconds(1)就变成等于了。。
多减几秒应该可以，这个明早试，我这只有早上才试得出来，白天怎么弄都是少一秒，奇了怪了。

不过还是建议$validUntil用 Token 的iat时间来加减，这样时间统一就不会出问题了。。

**Comment by yuanzhihai** [comment]
发了新版
使用了  Token 的iat时间 来 subSeconds(1)

**Comment by wybwsk** [comment]
完美解决。感谢作者，插件超级好用！
